### ISSUE TITLE
Error running forge server 1.19.2 - 43.1.16

### ISSUE THREAD

**Issue by FrederickEngelhardt** [mpbb/ironbows#1]
Does iron bows work on a forge 1.19.2 server? Getting a crash for 1.19.2 server using forge 1.19.2 - 43.1.16

Seeing this error

```
        ModLauncher naming: srg
        ModLauncher services:
                mixin-0.8.5.jar mixin PLUGINSERVICE
                eventbus-6.0.3.jar eventbus PLUGINSERVICE
                fmlloader-1.19.2-43.1.16.jar slf4jfixer PLUGINSERVICE
                fmlloader-1.19.2-43.1.16.jar object_holder_definalize PLUGINSERVICE
                fmlloader-1.19.2-43.1.16.jar runtime_enum_extender PLUGINSERVICE
                fmlloader-1.19.2-43.1.16.jar capability_token_subclass PLUGINSERVICE
                accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE
                fmlloader-1.19.2-43.1.16.jar runtimedistcleaner PLUGINSERVICE
                modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE
                modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE
        FML Language Providers:
                minecraft@1.0
                lowcodefml@null
                javafml@null
        Mod List:
                server-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft
        |1.19.2              |COMMON_SET|Manifest: NOSIGNATURE
                forge-1.19.2-43.1.16-universal.jar                |Forge                         |forge
        |43.1.16             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
                ironbows-1.19.2-1.2.jar                           |Iron Bows                     |ironbows
        |1.19.2-1.2          |ERROR     |Manifest: NOSIGNATURE
        Crash Report UUID: 11047382-f72a-4f14-85f6-6ef219408338
        FML: 43.1
        Forge: net.minecraftforge:43.1.16[15:48:06] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Iron Bows (ironbows) has failed to load correctly
?7java.lang.reflect.InvocationTargetException: null
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[fmlcore-1.19.2-43.1.16.jar%23101!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$24(ModLoader.java:208) ~[fmlcore-1.19.2-43.1.16.jar%23101!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:208) ~[fmlcore-1.19.2-43.1.16.jar%23101!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$14(ModLoader.java:185) ~[fmlcore-1.19.2-43.1.16.jar%23101!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:185) ~[fmlcore-1.19.2-43.1.16.jar%23101!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.19.2-43.1.16-universal.jar%23105!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23100!/:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.1.16.jar%2367!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
```

**Comment by mpbb** [comment]
Thank you for your issue, this will be investigated today.

**Comment by mpbb** [comment]
Fixed by latest commit
